server:
  port: 8105
hm:
  db:
    database: hm-pay
  swagger:
    title: 黑马商城接口文档
    desc: 黑马商城接口文档
    package-name: com.hmall.pay.controller

spring:
  rabbitmq:
    password: 123456
    username: hmall
    host: localhost
    port: 5672
    virtual-host: /hmall